### PR TITLE
lots of stuff

### PR DESCRIPTION
**Pull request by HEROOSTECH**

### CODE REVIEW

**Comment by HEROOSTECH** [comment]
@Window5000 Can i merge it?

**Comment by Window5000** [comment]
yes

**Comment by Window5000** [comment]
I added a release draft that you can publish if you want to.

**Comment by HEROOSTECH** [comment]
@Window5000 We can make WE for minestom here, why million forks?

**Comment by Window5000** [comment]
@HEROOSTECH What do you mean?

**Comment by HEROOSTECH** [comment]
> @HEROOSTECH What do you mean?

Just work on World Edit here if you want, next forks makes no sense.

**Comment by Window5000** [comment]
of course

**Comment by Window5000** [comment]
@HEROOSTECH Can you [make this fork independent](https://stackoverflow.com/a/47974224) and add `minestom-extension` as a topic?

**Pull request merged**
